openapi: 3.0.3
info:
  title: IT Center Leave & Attendance API
  version: 3.0.0
  description: |
    Serverless leave, attendance, integration, and reporting endpoints running on API Gateway → Lambda → PostgreSQL.

servers:
  - url: https://{apiId}.execute-api.ap-southeast-2.amazonaws.com
    description: AWS API Gateway invoke URL
    variables:
      apiId:
        default: dev-placeholder

paths:
  /healthz:
    get:
      summary: Health check
      tags: [System]
      operationId: healthz
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time

  /api/v1/leave/balance:
    get:
      summary: Get leave balances
      tags: [Leave]
      operationId: getLeaveBalance
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: query
          description: Optional user ID (ADMIN only, defaults to caller)
          schema:
            type: integer
        - name: year
          in: query
          description: Optional calendar year (defaults to current year)
          schema:
            type: integer
      responses:
        '200':
          description: Balances retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                  year:
                    type: integer
                  balances:
                    type: array
                    items:
                      $ref: '#/components/schemas/LeaveBalance'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/v1/leave/requests:
    get:
      summary: List leave requests
      tags: [Leave]
      operationId: listLeaveRequests
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: query
          description: Optional user filter (ADMIN only)
          schema:
            type: integer
        - name: status
          in: query
          schema:
            type: string
            enum: [PENDING, APPROVED, REJECTED, CANCELLED]
        - name: from
          in: query
          description: Start date (ISO 8601)
          schema:
            type: string
            format: date
        - name: to
          in: query
          description: End date (ISO 8601)
          schema:
            type: string
            format: date
        - name: page
          in: query
          description: 1-based page index
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: size
          in: query
          description: Page size (max 100)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
        - name: sort
          in: query
          description: Sort field and direction (e.g. created_at,desc)
          schema:
            type: string
            default: created_at,desc
      responses:
        '200':
          description: Paginated leave requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLeaveRequests'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: Create leave request
      tags: [Leave]
      operationId: createLeaveRequest
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLeaveRequest'
      responses:
        '201':
          description: Leave request created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveRequest'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '409':
          description: Overlapping request or insufficient balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/leave/requests/{id}:
    patch:
      summary: Update leave request status
      tags: [Leave]
      operationId: updateLeaveRequest
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLeaveRequest'
      responses:
        '200':
          description: Leave request updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveRequest'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/attendance:
    get:
      summary: List attendance logs
      tags: [Attendance]
      operationId: listAttendance
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: query
          description: Optional user filter (ADMIN only)
          schema:
            type: integer
        - name: from
          in: query
          description: Start timestamp (ISO 8601)
          schema:
            type: string
        - name: to
          in: query
          description: End timestamp (ISO 8601)
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
        - name: sort
          in: query
          schema:
            type: string
            default: clock_in,desc
      responses:
        '200':
          description: Paginated attendance logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAttendanceLogs'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/v1/attendance/clock-in:
    post:
      summary: Clock in
      tags: [Attendance]
      operationId: clockIn
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClockInRequest'
      responses:
        '201':
          description: Clock-in recorded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceLog'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '409':
          description: Active session already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/attendance/clock-out:
    post:
      summary: Clock out
      tags: [Attendance]
      operationId: clockOut
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClockOutRequest'
      responses:
        '200':
          description: Clock-out recorded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceLog'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '404':
          description: No active clock-in session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/integrations/msgraph/sync:
    post:
      summary: Enqueue Microsoft Graph calendar sync
      tags: [Integrations]
      operationId: enqueueMsGraphSync
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MsGraphSyncRequest'
      responses:
        '202':
          description: Sync queued
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Calendar sync enqueued
                  requestId:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Forbidden'

  /api/v1/reports/leave-summary:
    get:
      summary: Leave summary report
      tags: [Reports]
      operationId: getLeaveSummary
      security:
        - bearerAuth: []
      parameters:
        - name: from
          in: query
          description: Start date (ISO 8601)
          schema:
            type: string
            format: date
        - name: to
          in: query
          description: End date (ISO 8601)
          schema:
            type: string
            format: date
        - name: team_id
          in: query
          description: Optional team identifier
          schema:
            type: integer
      responses:
        '200':
          description: Report generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveSummary'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Forbidden'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LeaveBalance:
      type: object
      properties:
        balanceId:
          type: integer
        policyId:
          type: integer
        policyName:
          type: string
        balanceDays:
          type: number
        year:
          type: integer

    LeaveRequest:
      type: object
      properties:
        requestId:
          type: integer
        userId:
          type: integer
        userEmail:
          type: string
          format: email
        userName:
          type: string
          nullable: true
        policyId:
          type: integer
        policyName:
          type: string
        status:
          type: string
          enum: [PENDING, APPROVED, REJECTED, CANCELLED]
        startDate:
          type: string
        endDate:
          type: string
        halfDay:
          type: boolean
        graphEventId:
          type: string
          nullable: true
        daysRequested:
          type: number
        reason:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    PaginatedLeaveRequests:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LeaveRequest'
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer

    CreateLeaveRequest:
      type: object
      required:
        - policy_id
        - start_date
        - end_date
      properties:
        policy_id:
          type: integer
        start_date:
          type: string
        end_date:
          type: string
        half_day:
          type: boolean
          default: false
        reason:
          type: string
          nullable: true

    UpdateLeaveRequest:
      type: object
      required:
        - action
      properties:
        action:
          type: string
          enum: [APPROVE, REJECT, CANCEL]
        notes:
          type: string
          nullable: true

    AttendanceLog:
      type: object
      properties:
        logId:
          type: integer
        userId:
          type: integer
        clockIn:
          type: string
          format: date-time
        clockOut:
          type: string
          format: date-time
          nullable: true
        durationMinutes:
          type: integer
          nullable: true
        latitude:
          type: number
          nullable: true
        longitude:
          type: number
          nullable: true
        source:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time

    PaginatedAttendanceLogs:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/AttendanceLog'
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer

    ClockInRequest:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        source:
          type: string

    ClockOutRequest:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time

    MsGraphSyncRequest:
      type: object
      required:
        - request_id
      properties:
        request_id:
          type: integer

    LeaveSummary:
      type: object
      properties:
        range:
          type: object
          properties:
            from:
              type: string
              nullable: true
            to:
              type: string
              nullable: true
        policies:
          type: array
          items:
            type: object
            properties:
              policyId:
                type: integer
              policyName:
                type: string
              totalRequests:
                type: integer
              pending:
                type: integer
              approved:
                type: integer
              rejected:
                type: integer
              cancelled:
                type: integer
              approvedDays:
                type: number
        totals:
          type: object
          properties:
            totalRequests:
              type: integer
            pending:
              type: integer
            approved:
              type: integer
            rejected:
              type: integer
            cancelled:
              type: integer
            approvedDays:
              type: number

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
          nullable: true
        requestId:
          type: string
          description: AWS request identifier

  responses:
    Unauthenticated:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

security:
  - bearerAuth: []

