version: '3.8'

services:
  zap:
    image: owasp/zap2docker-stable
    container_name: zap-daemon
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8080", "-config", "api.disablekey=true"]
    ports:
      - "8081:8080" # expose ZAP API externally if needed
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - zap_net

  zap-web:
    image: owasp/zap2docker-stable
    depends_on:
      - zap
    volumes:
      - ../security:/zap/wrk
      - ../security-reports:/zap/reports
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [
      "zap-baseline.py",
      "-t", "http://host.docker.internal:5173",
      "--allow-missing-content",
      "--hook=/zap/wrk/hook.py",
      "--zap-url", "http://zap:8080",
      "-r", "/zap/reports/web-baseline.html",
      "-J", "/zap/reports/web-baseline.json",
      "-x", "/zap/reports/web-baseline.xml",
      "-I",
      "-z", "-config scanner.attackOnStart=false"
    ]
    networks:
      - zap_net

  zap-api:
    image: owasp/zap2docker-stable
    depends_on:
      - zap
    volumes:
      - ../security:/zap/wrk
      - ../security-reports:/zap/reports
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [
      "zap-baseline.py",
      "-t", "http://host.docker.internal:8080",
      "--allow-missing-content",
      "--hook=/zap/wrk/hook.py",
      "--zap-url", "http://zap:8080",
      "-r", "/zap/reports/api-baseline.html",
      "-J", "/zap/reports/api-baseline.json",
      "-x", "/zap/reports/api-baseline.xml",
      "-I",
      "-z", "-config scanner.attackOnStart=false"
    ]
    networks:
      - zap_net

networks:
  zap_net:
    driver: bridge


