version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: itcenter_pg
    environment:
      POSTGRES_DB: itcenter_auth
      POSTGRES_USER: itcenter
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U itcenter -d itcenter_auth"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - itcenter_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # Web UI for viewing emails
      - "1025:1025"  # SMTP server
    networks:
      - itcenter_network

volumes:
  postgres_data:

networks:
  itcenter_network:
    driver: bridge

