name: itcenter_auth
description: IT Center Staff Authentication Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # AWS Amplify
  amplify_flutter: ^2.4.2
  amplify_auth_cognito: ^2.4.2
  
  # Networking
  http: ^1.2.2
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  flutter_secure_storage: ^9.0.0
  
  # UI
  flutter_svg: ^2.0.9
  
  # Routing
  go_router: ^13.0.0
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

