spring:
  application:
    name: itcenter-auth-api
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/itcenter_auth}
    username: ${SPRING_DATASOURCE_USERNAME:itcenter}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
    show-sql: true
  
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: false
    repair-on-migrate: true
    out-of-order: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_hTAYJId8y}
          jwk-set-uri: ${COGNITO_JWK_SET_URI:https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_hTAYJId8y/.well-known/jwks.json}
          clock-skew: 120
  
cognito:
  user-pool-id: ${COGNITO_USER_POOL_ID:ap-southeast-2_hTAYJId8y}
  client-id: ${COGNITO_CLIENT_ID:3rdnl5ind8guti89jrbob85r4i}
  issuer-uri: ${COGNITO_ISSUER_URI:https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_hTAYJId8y}
  jwk-set-uri: ${COGNITO_JWK_SET_URI:https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_hTAYJId8y/.well-known/jwks.json}
  domain: ${COGNITO_DOMAIN:itcenter-auth.auth.ap-southeast-2.amazoncognito.com}
  region: ${AWS_REGION:ap-southeast-2}

server:
  port: ${BACKEND_PORT:8080}
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.itcenter: ${LOGGING_LEVEL_COM_ITCENTER:DEBUG}
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/auth-api.log

app:
  bootstrap-admin-email: ${BOOTSTRAP_ADMIN_EMAIL:admin@itcenter.com}
  audit-retention-days: ${AUDIT_RETENTION_DAYS:180}
  cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}

