// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Schedules.Api.Data;

#nullable disable

namespace Schedules.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124085128_Phase4Initial")]
    partial class Phase4Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Schedules.Api.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("jsonb");

                    b.Property<int>("FailureRows")
                        .HasColumnType("integer");

                    b.Property<long>("InitiatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SuccessRows")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_import_jobs_status");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.Recurrence", b =>
                {
                    b.Property<Guid>("RecurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ByDay")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short?>("BySetPosition")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("RepeatUntil")
                        .HasColumnType("date");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RecurrenceId");

                    b.ToTable("recurrences", (string)null);
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RecurrenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduleId");

                    b.HasIndex("RecurrenceId");

                    b.HasIndex("TeamId", "StartTime")
                        .HasDatabaseName("idx_schedules_team_start");

                    b.HasIndex("UserId", "StartTime")
                        .HasDatabaseName("idx_schedules_user_start");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("AssigneeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<long>("ReporterId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TaskId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("AssigneeId", "Status", "DueDate")
                        .HasDatabaseName("idx_tasks_assignee_status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.TaskNote", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Attachments")
                        .HasColumnType("jsonb");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("NoteId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_task_notes_task");

                    b.ToTable("task_notes", (string)null);
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Schedules.Api.Domain.Entities.Recurrence", "Recurrence")
                        .WithMany("Schedules")
                        .HasForeignKey("RecurrenceId");

                    b.Navigation("Recurrence");
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.TaskEntity", b =>
                {
                    b.HasOne("Schedules.Api.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Tasks")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.TaskNote", b =>
                {
                    b.HasOne("Schedules.Api.Domain.Entities.TaskEntity", "Task")
                        .WithMany("Notes")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.Recurrence", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Schedules.Api.Domain.Entities.TaskEntity", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
