// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Schedules.Infrastructure.Data;

#nullable disable

namespace Schedules.Infrastructure.Migrations
{
    [DbContext(typeof(SchedulesDbContext))]
    [Migration("20251124152816_Phase4Initial")]
    partial class Phase4Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Schedules.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("ImportJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text")
                        .HasColumnName("error_details");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("job_type");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_count");

                    b.Property<long>("RequestedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("ImportJobId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_import_jobs_status");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("Schedules.Domain.Entities.RecurrencePattern", b =>
                {
                    b.Property<Guid>("RecurrencePatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recurrence_id");

                    b.Property<string>("ByDay")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("by_day");

                    b.Property<string>("ByMonthDay")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("by_month_day");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("pattern");

                    b.Property<DateTimeOffset?>("Until")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("until");

                    b.HasKey("RecurrencePatternId");

                    b.ToTable("recurrences", (string)null);

                    b.HasData(
                        new
                        {
                            RecurrencePatternId = new Guid("aaaaaaaa-bbbb-cccc-dddd-444444444444"),
                            ByDay = "MO,WE,FR",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Interval = 1,
                            Pattern = "WEEKLY"
                        });
                });

            modelBuilder.Entity("Schedules.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<string>("CalendarEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("calendar_event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<Guid?>("RecurrenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ScheduleId");

                    b.HasIndex("RecurrenceId");

                    b.HasIndex("UserId", "StartTime")
                        .HasDatabaseName("idx_schedules_user_start");

                    b.HasIndex("UserId", "StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("schedules", (string)null);

                    b.HasData(
                        new
                        {
                            ScheduleId = new Guid("aaaaaaaa-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            Description = "Seeded schedule for QA validation",
                            EndTime = new DateTimeOffset(new DateTime(2025, 1, 6, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsAllDay = false,
                            RecurrenceId = new Guid("aaaaaaaa-bbbb-cccc-dddd-444444444444"),
                            Source = "Internal",
                            StartTime = new DateTimeOffset(new DateTime(2025, 1, 6, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Confirmed",
                            TeamId = 10L,
                            Title = "Sample Onsite Shift",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Schedules.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<long>("AssigneeId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("MsGraphItemId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ms_graph_item_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TaskItemId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("AssigneeId", "Status")
                        .HasDatabaseName("idx_tasks_assignee_status");

                    b.ToTable("tasks", (string)null);

                    b.HasData(
                        new
                        {
                            TaskItemId = new Guid("aaaaaaaa-bbbb-cccc-dddd-222222222222"),
                            AssigneeId = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 2L,
                            Description = "Initial seeded task for smoke testing",
                            DueDate = new DateTimeOffset(new DateTime(2025, 1, 7, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = "High",
                            ScheduleId = new Guid("aaaaaaaa-bbbb-cccc-dddd-111111111111"),
                            Status = "InProgress",
                            Tags = new[] { "seed", "demo" },
                            Title = "Seed Task",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Schedules.Domain.Entities.TaskNote", b =>
                {
                    b.Property<Guid>("TaskNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TaskNoteId");

                    b.HasIndex("TaskItemId")
                        .HasDatabaseName("idx_task_notes_task");

                    b.ToTable("task_notes", (string)null);

                    b.HasData(
                        new
                        {
                            TaskNoteId = new Guid("aaaaaaaa-bbbb-cccc-dddd-333333333333"),
                            AuthorId = 2L,
                            Body = "Seeded comment for validation.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TaskItemId = new Guid("aaaaaaaa-bbbb-cccc-dddd-222222222222"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Schedules.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Schedules.Domain.Entities.RecurrencePattern", "Recurrence")
                        .WithMany("Schedules")
                        .HasForeignKey("RecurrenceId");

                    b.Navigation("Recurrence");
                });

            modelBuilder.Entity("Schedules.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Schedules.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Tasks")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Schedules.Domain.Entities.TaskNote", b =>
                {
                    b.HasOne("Schedules.Domain.Entities.TaskItem", "Task")
                        .WithMany("Notes")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Schedules.Domain.Entities.RecurrencePattern", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Schedules.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Schedules.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
